### ISSUE TITLE
wwwroot is not found

### ISSUE THREAD

**Issue by xulihang** [danroth27/BlazorWinForms#1]
If I use Visual Studio to run the project, it works fine. But If I distribute the program to another computer, it will have this error.

I found that in `BlazorWinForms.staticwebassets.runtime.json`, it has a `ContentRoots` property which is the absolute path to the `wwwroot`.

How to solve this so that the program will use the `wwwroot` placed along with the program?

**Comment by xulihang** [comment]
I just deleted `BlazorWinForms.staticwebassets.runtime.json`, which seems to work.

**Comment by xulihang** [comment]
If I publish a self-contained package, there will be no `BlazorWinForms.staticwebassets.runtime.json`.

```
dotnet publish -c Release -r win-x64 --self-contained
```

**Comment by danroth27** [comment]
@xulihang Could you please describe the exact steps that you used original to distribute the program to another computer that then resulted in the error? We'd like to investigate this happened.

**Comment by xulihang** [comment]
I think it is my mistake.

I just used the release build and did not publish the solution. The latter works.

```
System.IO.DirectoryNotFoundException: C:\Users\admin\source\repos\Blazor\WinFormsApp1\WinFormsApp1\wwwroot\
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Components.WebView.WebViewManager.StaticWebAssetsLoader.<>c.<UseStaticWebAssets>b__0_0(String path)
   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
   at Microsoft.AspNetCore.Components.WebView.WebViewManager.StaticWebAssetsLoader.UseStaticWebAssets(IFileProvider fileProvider)
   at Microsoft.AspNetCore.Components.WebView.WebViewManager..ctor(IServiceProvider provider, Dispatcher dispatcher, Uri appBaseUri, IFileProvider fileProvider, JSComponentConfigurationStore jsComponents, String hostPageRelativePath)
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.BlazorWebView.StartWebViewCoreIfPossible()
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.BlazorWebView.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

```

**Comment by danroth27** [comment]
@xulihang Ah, ok. Publishing is required before deployment. Thanks for trying out Blazor with WinForms!

**Comment by xulihang** [comment]
I've written a blog about using Blazor in WinForms: [Combine Blazor and WinFroms to Build a Document Scanning Desktop App](https://www.dynamsoft.com/codepool/blazor-webview-winforms-document-scanner.html)
